// DGX Prototype 1.7.1 — the 11 real seed extraction profiles (spec §16).
// Real configuration reflecting each document type's actual real fields in
// this environment (e.g. LUBRICANT_TDS mirrors the real Liqui Moly fields
// this phase actually extracts — SpecGrade/Approvals/SpecificationItems —
// not an imagined generic shape).
import type { ExtractionProfileFieldRules } from './extraction-profile.service';

export const SEED_EXTRACTION_PROFILES: Record<string, ExtractionProfileFieldRules> = {
  LUBRICANT_TDS: {
    requiredMetadata: ['articleNumber', 'name', 'specGrade'],
    expectedSections: ['specification', 'approvals'],
    candidateEntities: ['viscosityGrade', 'apiSpecification', 'aceaSpecification'],
    candidateClaimTypes: ['fluid_specification'],
    structuredFactTypes: ['FLUID_TYPE', 'FLUID_CAPACITY', 'LUBRICANT_APPROVAL'],
    highRiskFields: ['specGrade', 'approvals'],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: ['missing_spec_grade_and_approvals'],
  },
  LUBRICANT_PDS: {
    requiredMetadata: ['articleNumber', 'name'],
    expectedSections: ['product_description', 'packaging'],
    candidateEntities: ['packagingSize', 'category'],
    candidateClaimTypes: ['fluid_specification'],
    structuredFactTypes: ['FLUID_CAPACITY'],
    highRiskFields: [],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: [],
  },
  SAFETY_DATA_SHEET: {
    requiredMetadata: ['productName', 'hazardClassification'],
    expectedSections: ['hazard_identification', 'handling_and_storage', 'disposal'],
    candidateEntities: ['hazardCode', 'casNumber'],
    candidateClaimTypes: ['approval_statement'],
    structuredFactTypes: ['OTHER'],
    highRiskFields: ['hazardClassification'],
    approvalRoles: ['SAFETY_REVIEWER'],
    rejectionRules: ['missing_hazard_identification'],
  },
  PARTS_CATALOGUE: {
    requiredMetadata: ['articleNumber', 'canonicalOemNumber'],
    expectedSections: ['fitment', 'specifications'],
    candidateEntities: ['oemNumber', 'partGroup'],
    candidateClaimTypes: ['fitment_statement'],
    structuredFactTypes: ['FITMENT', 'PART_DIMENSION'],
    highRiskFields: ['canonicalOemNumber'],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: ['missing_oem_number'],
  },
  FITMENT_EXPORT: {
    requiredMetadata: ['articleId', 'vehicleId'],
    expectedSections: [],
    candidateEntities: ['vehicleId', 'modelId'],
    candidateClaimTypes: ['fitment_statement'],
    structuredFactTypes: ['FITMENT'],
    highRiskFields: ['vehicleId'],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: [],
  },
  TECHNICAL_BULLETIN: {
    requiredMetadata: ['bulletinNumber', 'affectedVehicles'],
    expectedSections: ['issue_description', 'remedy'],
    candidateEntities: ['vehicleModel', 'engineCode'],
    candidateClaimTypes: ['approval_statement', 'supersession_statement'],
    structuredFactTypes: ['OTHER'],
    highRiskFields: ['affectedVehicles'],
    approvalRoles: ['TECHNICAL_REVIEWER', 'SAFETY_REVIEWER'],
    rejectionRules: ['missing_affected_vehicles'],
  },
  WORKSHOP_SOP: {
    requiredMetadata: ['procedureTitle'],
    expectedSections: ['scope', 'procedure', 'safety'],
    candidateEntities: ['tool', 'torqueValue'],
    candidateClaimTypes: ['torque_value', 'service_interval'],
    structuredFactTypes: ['TORQUE_SPEC', 'SERVICE_INTERVAL'],
    highRiskFields: ['torqueValue'],
    approvalRoles: ['TECHNICAL_REVIEWER', 'SAFETY_REVIEWER'],
    rejectionRules: [],
  },
  DIAGNOSTIC_PROCEDURE: {
    requiredMetadata: ['procedureTitle'],
    expectedSections: ['symptoms', 'diagnostic_steps', 'suspected_causes'],
    candidateEntities: ['diagnosticCode', 'suspectedCause'],
    candidateClaimTypes: ['approval_statement'],
    structuredFactTypes: ['DIAGNOSTIC_THRESHOLD'],
    highRiskFields: [],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: [],
  },
  WARRANTY_POLICY: {
    requiredMetadata: ['policyTitle', 'coveragePeriod'],
    expectedSections: ['eligibility', 'exclusions'],
    candidateEntities: ['coveragePeriod'],
    candidateClaimTypes: ['approval_statement'],
    structuredFactTypes: ['WARRANTY_TERM'],
    highRiskFields: ['coveragePeriod'],
    approvalRoles: ['LICENSING_REVIEWER', 'FINAL_APPROVER'],
    rejectionRules: ['missing_coverage_period'],
  },
  INTERNAL_CASE_RECORD: {
    requiredMetadata: ['caseId', 'classification'],
    expectedSections: ['complaint', 'diagnosis', 'action', 'outcome'],
    candidateEntities: ['diagnosticCode', 'partUsed'],
    candidateClaimTypes: ['approval_statement'],
    structuredFactTypes: ['OTHER'],
    highRiskFields: [],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: ['missing_outcome'],
  },
  PRODUCT_SUPERSESSION_NOTICE: {
    requiredMetadata: ['oldArticleNumber', 'newArticleNumber', 'effectiveDate'],
    expectedSections: ['reason', 'effective_date'],
    candidateEntities: ['articleNumber'],
    candidateClaimTypes: ['supersession_statement'],
    structuredFactTypes: ['OTHER'],
    highRiskFields: ['newArticleNumber'],
    approvalRoles: ['TECHNICAL_REVIEWER'],
    rejectionRules: ['missing_new_article_number'],
  },
};
