// Phase 2 permission set. Deliberately a code-level constant map rather than
// a DB-backed permission table — Phase 2 doesn't need runtime-editable
// permissions, and a static map is trivially auditable by reading the file.
// See docs/architecture/rbac-permissions.md.
export const PERMISSIONS = [
  'organization.read',
  'organization.manage',
  'warehouse.read',
  'warehouse.manage',
  'customer.read',
  'customer.manage',
  'parts.read',
  'parts.manage',
  'lubricants.read',
  'lubricants.manage',
  'sales.read',
  'sales.import',
  'purchases.read',
  'purchases.import',
  'inventory.read',
  'inventory.adjust',
  'logs.read',
  'logs.import',
  'lostSales.read',
  'lostSales.review',
  'recommendations.read',
  'recommendations.generate',
  'recommendations.approve',
  'supplierAnalytics.read',
  'audit.read',
  // Phase 3 — garage operations (see docs/architecture/garage-rbac.md)
  'reception.read',
  'reception.manage',
  'jobcard.read',
  'jobcard.manage',
  'jobcard.transition',
  'inspection.read',
  'inspection.manage',
  'diagnostics.read',
  'diagnostics.manage',
  'estimate.read',
  'estimate.manage',
  'estimate.approve',
  'labour.read',
  'labour.manage',
  'technician.read',
  'technician.manage',
  'qc.read',
  'qc.manage',
  'timeline.read',
  'notifications.read',
  'notifications.manage',
  // Phase 4 — DGX AI platform (see docs/architecture/ai-governance.md)
  'ai.chat',
  'ai.vehicleHealth',
  'ai.forecast.read',
  'ai.forecast.generate',
  'ai.recommend',
  'ai.technicianAssistant',
  'ai.managerAssistant',
  'ai.modelRegistry.read',
  'ai.modelRegistry.manage',
  'ai.prompts.read',
  'ai.prompts.manage',
  'ai.evaluations.read',
  'ai.evaluations.manage',
  'ai.knowledgeBase.read',
  'ai.knowledgeBase.manage',
  'ai.feedback.manage',
  // Phase 5 — Enterprise Platform (see docs/architecture/authorization.md
  // for the mapping table between the spec's example permission names,
  // e.g. "garage.jobs.create"/"inventory.issue"/"vehicle.edit", and this
  // system's existing granular permissions above — most of the spec's
  // examples were already covered by Phase 2/3/4 permissions and are not
  // duplicated here under a second name).
  'system.admin',
  'identity.manage',
  'apikeys.manage',
  'security.read',
  'integration.manage',
  'branchGateway.read',
  'branchGateway.manage',
  'backup.manage',
  'observability.read',
  // Data Consolidation phase (docs/data-consolidation/*.md)
  'dataSources.read',
  'dataSources.manage',
  'dataProfiles.read',
  'imports.execute',
  'imports.reconcile',
  'mappings.read',
  'mappings.review',
  'mappings.approve',
  'dataQuality.read',
  'dataQuality.resolve',
  // Data Validation, Business Baselining & AI Readiness phase (docs/data-readiness/*.md)
  'dataAuthority.read',
  'dataAuthority.manage',
  'reviewQueue.read',
  'reviewQueue.assign',
  'reviewQueue.decide',
  'reviewQueue.undo',
  'baseline.read',
  'baseline.generate',
  'baseline.approve',
  'dataQuality.profile',
  'dataSnapshots.read',
  'dataSnapshots.create',
  'aiDatasets.read',
  'aiDatasets.build',
  'aiDatasets.approve',
  'aiReadiness.read',
  'aiReadiness.manage',
  'forecastBaseline.run',
  'forecastBaseline.read',
  // DGX Prototype 1.7 — Automotive Knowledge Platform (see
  // docs/knowledge-platform/permissions-and-roles.md). 21 new strings, not
  // padded to a round number — DGX Prototype 1.6 added zero new
  // permissions (reused ai.evaluations.*/ai.prompts.*), but this phase
  // genuinely introduces new resource classes (source registry, structured
  // facts, snapshots, graph) that don't fit any existing permission.
  'knowledgeSource.read',
  'knowledgeSource.manage',
  'knowledgeSource.verifyLicense',
  'knowledgeItem.read',
  'knowledgeItem.draft',
  'knowledgeItem.manage',
  'knowledgeItem.approve',
  'knowledgeItem.publish',
  'knowledgeItem.withdraw',
  'knowledgeReview.read',
  'knowledgeReview.assign',
  'knowledgeReview.decide',
  'structuredFact.read',
  'structuredFact.manage',
  'structuredFact.review',
  'knowledgeConflict.read',
  'knowledgeConflict.resolve',
  'knowledgeSnapshot.read',
  'knowledgeSnapshot.manage',
  'knowledgeGraph.read',
  'knowledgeGraph.manage',
  'knowledgeRetrieval.query',
  'knowledgeSecurity.read',
  // DGX Prototype 1.7.2 — Retrieval Intelligence Platform.
  'retrievalIntelligence.query',
  'retrievalIntelligence.manage',
  // Platform Remediation PEP-3 — Permission Migration (WP-3.0, see
  // docs/governance/DGX3_PLATFORM_REMEDIATION_TECHNICAL_SPECIFICATION_1.md
  // §4, PRTS-003). Migrates integration/parts/vehicles off RolesGuard's
  // direct x-user-role header read onto PermissionsGuard. Each grant in
  // role-permissions.ts is an exact match to that endpoint's pre-migration
  // @Roles(...) list — no role gains or loses access. Controller migration
  // itself is out of scope for WP-3.0; these constants are unused until
  // WP-3.1/3.2/3.3.
  'integration.sync',
  'integration.deadLetters.read',
  'integration.deadLetters.resolve',
  'parts.create',
  'parts.matchCandidates.manage',
  'vehicle.create',
  'vehicle.correct',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
