import { Role } from '@prisma/client';
import { Permission, PERMISSIONS } from './permission';

const ALL_READ: Permission[] = [
  'organization.read',
  'warehouse.read',
  'customer.read',
  'parts.read',
  'lubricants.read',
  'sales.read',
  'purchases.read',
  'inventory.read',
  'logs.read',
  'lostSales.read',
  'recommendations.read',
  'supplierAnalytics.read',
  'audit.read',
  'reception.read',
  'jobcard.read',
  'inspection.read',
  'diagnostics.read',
  'estimate.read',
  'labour.read',
  'technician.read',
  'qc.read',
  'timeline.read',
  'notifications.read',
  'ai.chat',
  'ai.vehicleHealth',
  'ai.forecast.read',
  'ai.recommend',
  'ai.technicianAssistant',
  'ai.managerAssistant',
  'ai.modelRegistry.read',
  'ai.prompts.read',
  'ai.evaluations.read',
  'ai.knowledgeBase.read',
  'security.read',
  'branchGateway.read',
  'observability.read',
  'dataSources.read',
  'dataProfiles.read',
  'mappings.read',
  'dataQuality.read',
  'dataAuthority.read',
  'reviewQueue.read',
  'baseline.read',
  'dataSnapshots.read',
  'aiDatasets.read',
  'aiReadiness.read',
  'forecastBaseline.read',
  // DGX Prototype 1.7 — required convention: every new `.read`/`.query`
  // permission must be manually appended here too, it is not automatic.
  'knowledgeSource.read',
  'knowledgeItem.read',
  'knowledgeReview.read',
  'structuredFact.read',
  'knowledgeConflict.read',
  'knowledgeSnapshot.read',
  'knowledgeGraph.read',
  'knowledgeRetrieval.query',
  'knowledgeSecurity.read',
  'retrievalIntelligence.query',
];

// Explicit per-role grants rather than a clever "inherits from" hierarchy —
// each role's permission set can be read in one place without tracing a
// chain. See docs/architecture/rbac-permissions.md for the rationale and for
// which scopes (branch/warehouse) are placeholders, not fully enforced.
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SYSTEM_ADMINISTRATOR]: [...PERMISSIONS],
  [Role.OWNER]: [...PERMISSIONS],
  [Role.GENERAL_MANAGER]: [
    ...ALL_READ,
    'organization.manage',
    'warehouse.manage',
    'customer.manage',
    'parts.manage',
    'lubricants.manage',
    'sales.import',
    'purchases.import',
    'inventory.adjust',
    'logs.import',
    'lostSales.review',
    'recommendations.generate',
    'recommendations.approve',
    'reception.manage',
    'jobcard.manage',
    'jobcard.transition',
    'inspection.manage',
    'diagnostics.manage',
    'estimate.manage',
    'estimate.approve',
    'labour.manage',
    'technician.manage',
    'qc.manage',
    'notifications.manage',
    'ai.forecast.generate',
    'ai.modelRegistry.manage',
    'ai.prompts.manage',
    'ai.evaluations.manage',
    'ai.knowledgeBase.manage',
    'ai.feedback.manage',
    'system.admin',
    'identity.manage',
    'apikeys.manage',
    'integration.manage',
    'branchGateway.manage',
    'backup.manage',
    'dataSources.manage',
    'imports.execute',
    'imports.reconcile',
    'mappings.review',
    'mappings.approve',
    'dataQuality.resolve',
    'dataAuthority.manage',
    'reviewQueue.assign',
    'reviewQueue.decide',
    'reviewQueue.undo',
    'baseline.generate',
    'baseline.approve',
    'dataQuality.profile',
    'dataSnapshots.create',
    'aiDatasets.build',
    'aiDatasets.approve',
    'aiReadiness.manage',
    'forecastBaseline.run',
    // DGX Prototype 1.7 — final-approve/publish verbs, consistent with
    // this role already holding ai.evaluations.manage/ai.knowledgeBase.manage.
    'knowledgeSource.manage',
    'knowledgeSource.verifyLicense',
    'knowledgeItem.approve',
    'knowledgeItem.publish',
    'knowledgeItem.withdraw',
    'structuredFact.manage',
    'knowledgeConflict.resolve',
    'knowledgeSnapshot.manage',
    'knowledgeGraph.manage',
  ],
  [Role.BRANCH_MANAGER]: [
    ...ALL_READ,
    'customer.manage',
    'inventory.adjust',
    'lostSales.review',
    'recommendations.approve',
    'jobcard.transition',
    'estimate.approve',
    'notifications.manage',
    'ai.forecast.generate',
    'ai.feedback.manage',
  ],
  [Role.PARTS_MANAGER]: [
    'parts.read',
    'parts.manage',
    'inventory.read',
    'sales.read',
    'purchases.read',
    'lostSales.read',
    'lostSales.review',
    'recommendations.read',
    'recommendations.generate',
    'ai.chat',
    'ai.recommend',
    'ai.forecast.read',
    'ai.knowledgeBase.read',
  ],
  [Role.LUBRICANTS_MANAGER]: [
    'lubricants.read',
    'lubricants.manage',
    'inventory.read',
    'sales.read',
    'purchases.read',
    'lostSales.read',
    'recommendations.read',
    'recommendations.generate',
    'ai.chat',
    'ai.recommend',
    'ai.forecast.read',
    'ai.knowledgeBase.read',
  ],
  [Role.STOREKEEPER]: ['warehouse.read', 'inventory.read', 'inventory.adjust', 'purchases.read', 'sales.read'],
  [Role.PURCHASING_OFFICER]: ['purchases.read', 'purchases.import', 'supplierAnalytics.read', 'recommendations.read'],
  [Role.PURCHASING_MANAGER]: [
    'purchases.read',
    'purchases.import',
    'supplierAnalytics.read',
    'inventory.read',
    'recommendations.read',
    'recommendations.generate',
    'recommendations.approve',
    'ai.recommend',
    'ai.forecast.read',
  ],
  [Role.SALESPERSON]: ['sales.read', 'customer.read', 'parts.read', 'lubricants.read', 'inventory.read'],
  [Role.DATA_QUALITY_REVIEWER]: [
    'logs.read',
    'logs.import',
    'sales.read',
    'purchases.read',
    'inventory.read',
    'audit.read',
    'dataSources.read',
    'dataProfiles.read',
    'mappings.read',
    'mappings.review',
    'dataQuality.read',
    'dataQuality.resolve',
    'dataAuthority.read',
    'reviewQueue.read',
    'reviewQueue.assign',
    'reviewQueue.decide',
    'dataQuality.profile',
    'baseline.read',
    'dataSnapshots.read',
    'aiReadiness.read',
    'forecastBaseline.read',
  ],
  [Role.AUDITOR]: [...ALL_READ],
  [Role.READ_ONLY_VIEWER]: [...ALL_READ],

  // Phase 3 garage roles — see docs/architecture/garage-rbac.md
  [Role.GARAGE_MANAGER]: [
    'reception.read',
    'reception.manage',
    'jobcard.read',
    'jobcard.manage',
    'jobcard.transition',
    'inspection.read',
    'inspection.manage',
    'diagnostics.read',
    'estimate.read',
    'estimate.manage',
    'estimate.approve',
    'labour.read',
    'labour.manage',
    'technician.read',
    'technician.manage',
    'qc.read',
    'qc.manage',
    'timeline.read',
    'notifications.read',
    'notifications.manage',
    'inventory.read',
    'inventory.adjust',
    'recommendations.read',
    'recommendations.generate',
    'customer.read',
    'ai.chat',
    'ai.vehicleHealth',
    'ai.recommend',
    'ai.technicianAssistant',
    'ai.managerAssistant',
    'ai.forecast.read',
    'ai.knowledgeBase.manage',
    'ai.feedback.manage',
  ],
  [Role.WORKSHOP_SUPERVISOR]: [
    'reception.read',
    'jobcard.read',
    'jobcard.manage',
    'jobcard.transition',
    'inspection.read',
    'inspection.manage',
    'diagnostics.read',
    'diagnostics.manage',
    'labour.read',
    'labour.manage',
    'technician.read',
    'technician.manage',
    'qc.read',
    'qc.manage',
    'timeline.read',
    'notifications.read',
    'notifications.manage',
    'inventory.read',
    'ai.chat',
    'ai.vehicleHealth',
    'ai.technicianAssistant',
    'ai.feedback.manage',
  ],
  [Role.RECEPTION]: ['reception.read', 'reception.manage', 'jobcard.read', 'customer.read', 'timeline.read', 'notifications.read'],
  [Role.TECHNICIAN]: [
    'jobcard.read',
    'jobcard.transition',
    'inspection.read',
    'inspection.manage',
    'diagnostics.read',
    'diagnostics.manage',
    'labour.read',
    'labour.manage',
    'technician.read',
    'timeline.read',
    'inventory.read',
    'ai.chat',
    'ai.technicianAssistant',
    'ai.feedback.manage',
  ],
  [Role.DIAGNOSTIC_TECHNICIAN]: [
    'jobcard.read',
    'diagnostics.read',
    'diagnostics.manage',
    'inspection.read',
    'inspection.manage',
    'timeline.read',
    'ai.chat',
    'ai.technicianAssistant',
    'ai.vehicleHealth',
    'ai.feedback.manage',
  ],
  [Role.QUALITY_INSPECTOR]: ['jobcard.read', 'qc.read', 'qc.manage', 'inspection.read', 'timeline.read', 'ai.chat'],
  [Role.SERVICE_ADVISOR]: [
    'reception.read',
    'jobcard.read',
    'estimate.read',
    'estimate.manage',
    'customer.read',
    'customer.manage',
    'timeline.read',
    'notifications.read',
    'notifications.manage',
    'ai.chat',
    'ai.vehicleHealth',
    'ai.recommend',
  ],

  // DGX Prototype 1.7 — Automotive Knowledge Platform (see
  // docs/knowledge-platform/permissions-and-roles.md). A dedicated
  // technical/licensing knowledge-review persona — everything except
  // final-approve/publish/withdraw, which stay with GENERAL_MANAGER.
  [Role.KNOWLEDGE_STEWARD]: [
    'knowledgeSource.read',
    'knowledgeSource.manage',
    'knowledgeSource.verifyLicense',
    'knowledgeItem.read',
    'knowledgeItem.draft',
    'knowledgeItem.manage',
    'knowledgeReview.read',
    'knowledgeReview.assign',
    'knowledgeReview.decide',
    'structuredFact.read',
    'structuredFact.manage',
    'structuredFact.review',
    'knowledgeConflict.read',
    'knowledgeConflict.resolve',
    'knowledgeSnapshot.read',
    'retrievalIntelligence.query',
    'retrievalIntelligence.manage',
    'knowledgeGraph.read',
    'knowledgeGraph.manage',
    'knowledgeRetrieval.query',
    'knowledgeSecurity.read',
    'ai.knowledgeBase.read',
  ],
};
